version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: redesocial
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    networks:
      cat-network:
        ipv4_address: 172.18.0.2
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

networks:
  cat-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

